template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "uppe1437"
__REPO__ = "lang-tau"
__UND2C__ = "tau"
__UNDEFINED__ = "Upper Tanana"
__UND__ = "tau"
