template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "uppe1437"
__REPO__ = "lang-tau"
__UND2C__ = "tau"
__UNDEFINED__ = "Upper Tanana"
__UND__ = "tau"
