template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "uppe1437"
__REPO__ = "lang-tau"
__UND2C__ = "tau"
__UNDEFINED__ = "Upper Tanana"
__UND__ = "tau"
